### ISSUE TITLE
Disable logging for the endpoint '/api/ping'

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/vc-room#13]
The app currently uses [morgan](https://www.npmjs.com/package/morgan) for logging. Exclude the logging for the endpoint `/api/ping` in the server.

Currently, the logging code is [at line 35 of index.js](https://github.com/TheNinza/vc-room/blob/4c472dd0f5ea1183422a17f8c5395100c2202440/index.js#L35).

Feel free to ask for any explanation or help.

**Comment by XoMute** [comment]
Hi @TheNinza 
I'd like to work on this issue

**Comment by TheNinza** [comment]
Hey @XoMute, sure go ahead with it.
